"""Initial migration

Revision ID: b228d908ea7d
Revises: 
Create Date: 2026-05-14 19:47:03.711725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b228d908ea7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_product') as batch_op:
        batch_op.create_unique_constraint('unique_sheet_product', ['sheet_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_product', schema=None) as batch_op:
        batch_op.drop_constraint('unique_sheet_product', type_='unique')

    # ### end Alembic commands ###
